/*
 * This source file was generated by the Gradle 'init' task
 */
package wtf.opal;

import org.junit.jupiter.api.Test;
import wtf.opal.sdk.Library;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
